version: "3.8"

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydb?schema=public
  
    volumes:
    - db.sqlite3:/usr/src/app/prisma/dev.db
